version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Rome"
    commit-message:
      prefix: "deps"
      prefix-development: "devDeps"
      include: "scope"
    assignees:
      - "NotReallyEight"
    reviewers:
      - "NotReallyEight"