name: GitHub actions

on:
  push:
    branches: [main]

jobs:
  check-eslint:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
      - run: npm run documentate
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out/
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}